apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: guardrails

resources:
  - namespace.yaml
  - postgres/configmap-seed.yaml
  - postgres/deployment.yaml
  - guardian/deployment.yaml
  - nemo-guardrails/configmap-policy.yaml
  - nemo-guardrails/deployment.yaml
